### ISSUE TITLE
Create uml of server classes

### ISSUE THREAD

**Issue by PtpJam** [ManagementTestTeam/coffee_server#2]

**Comment by Shadplant** [comment]
![Server UML](https://user-images.githubusercontent.com/65445243/123778113-75c0bb00-d8d9-11eb-9a6b-afa4bd849060.png)

**Comment by Shadplant** [comment]
https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=Server%20UML.png#R7VjLbuIwFP2aSJ1FR%2BQBpUsC7XQkKqEyj3ZpYkOsOnHGMa9%2B%2FVwndp6kAyNQN5VY2MfXDvecY8c3ljuOdt8ESsJHjgmznB7eWe7EchzbcxxL%2FXp4nyM3t14OrATFOqgE5vSNaLCn0TXFJK0FSs6ZpEkdDHgck0DWMCQE39bDlpzVn5qgFWkB8wCxNvqbYhnm6NC5KfEHQlehebI9uM1HImSCdSZpiDDfViD3znLHgnOZt6LdmDBFnuEln3ffMVr8MUFiecwE%2BYJv%2BNOcLNjz26%2BNE%2F7pjebXepUNYmudsDV2rJFPY0nEEgVEdX3fcgYMHuIvBLRWqlUgBvg%2B8e9RgDAxI%2FBPFmV0xoDcG1pDGTFo2cXYhghJdp2p2QVh4DTCIyLFHkL0BOdWc6xN5hrOt6VktnFUWJGrrzGkXbIqli6JhIbm8gRe3RavJT0NKtItjRiKoecveSznekRRgxhdxdAOiJIDAMUSBXOO9IDkCaBBSBmeoj1fq7RSiYJX0%2FNDLugbLIsM3TAspN5nzqAWMVczAe4BKkgKMTMjgd2AHtGuFjhFqdRAwBlDSUoXRRoREisa%2B1xKHumgc4hu10X37LbohTGqotvu8EKq99u7qak2o5nSqRT8tThRFElLytiYMw4yT2KeBRn5GVnKA%2BJHFGOWLZaggMarH8oMk2u7RKbZxIlbIk%2BaBgUJLpFEuUxKE4YWhM14SiXlan2Rx%2FoJh9Mgo6rvW%2F1Jhgg55jEkgWgmFgH5tySVxyrbvWfacmt5watHqXspbe0DR6UD2fZGaxlCYqCM4u0KSAGeAZ9yML3ljDP9NTZDafqA0vCL5Y6gu4A3WcshwJssHNJwxOkmyU%2BIuh%2B8th8UxGHukmWvqBCsReIDHql7wQf%2Bx72vfeUKSLTv22X%2Fw4ziescZxRjq7E4ZdBhFCa8McFWzg7aCwT7NcFYzDI58J1zMDLbzjhuyI6JxYnz64ZJ%2BGB75FrmcH9o3w9wPP%2BOwwxHglE9TXNIUttmkH%2BaK4b8vjiTGI1XPQm%2FBuLqn%2BwDpi7w9yLv3VD03471SYQE3Yv%2BscCBad1%2BqYxNzmc97%2B9olneBWhdy4okNJDjd88p4AHVf5an1mjmpBGNykNvVnHmJcLzdTBivLAtfrHy4LzBIpX4uA6FnVermxUL%2FXqC8GjYXypFsLZQYocvx%2FT9y2PNFRQOrtXxH81JOgs74sSoxtSCWZJ%2BqDgDvZCpRkO30dY4Kts1V0ntco4w%2B8vb1D2%2FL0Kh665ZeXXLHy%2B5V79xc%3D

**Comment by Shadplant** [comment]
https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=Server%20UML.png#R7Vhbb9owGP01kboHptyg8EigXScxCZVd2keTmMSqE2eOufXX73Ni5wobTKC%2BIPFgH3%2B28TnHdj4bziTefeEojb6xAFPDNoOd4UwN27Zc2zbkzwz2BXI%2Fcgsg5CRQQRWwIO9YgaZC1yTAWSNQMEYFSZugz5IE%2B6KBIc7Zthm2YrQ5a4pC3AEWPqJd9BcJRFSgQ%2Fu%2Bwp8wCSM9szUYFS0x0sFqJVmEAratQc6D4Uw4Y6IoxbsJppI8zUvR7%2FFIa%2FnHOE7EKR3Ea3DPnhd4SV%2Fef27s6Lc5XvTUKBtE12rBxsQ2xh5JBOYr5GNZ9TzDHlCYxFtyKIWyVCIa%2BDr1HpGPAqxb4J8sq%2BicAbHXtEYiplCyyrYN5gLvji7NKgkDp2EWY8H3EKI62CPFsTKZoznfVpJZ2lFRTa6%2BwpBySVgOXREJBcXlGbw6HV4relpUZFsSU5RAzVuxRCxUi6QGURImUPaxlAMAyRIBc45Vg2ApoH5EaDBDe7aWy8oE8t90zYsYJ%2B8wLNJ0QzMXap%2FZg0bEQvYE2ASU4wxi5loCqwV9Q7tG4AxlQgE%2BoxSlGVmWy4gRD0niMSFYrIIuIbrVFN21uqKXxqiLbg3cK6ne7%2B6mttqU5EpngrO38kSRJK0IpRNGGcg8TVgepOWneCUOiB%2BTIKD5YCnySRJ%2Bl2aY9qwKmeUdp06FPCsaJMSZQAIVMklNKFpiOmcZEYTJ8XkR66UMToOcqr5n9Kc5wsWEJbAIRHKxMMi%2FxZk4Vdnje6Yrt5IXvHqSusMraWu5B8SF1ZrPOCSSCcnaHRSAZUBnDCxv2JNcfYXNUZY9oSz6ZDhjORKDCdv%2BANZE6Y%2BWH863SHE%2BNN3gdt0gIQZ9VzS%2FoCIwFk4OOKTpBA%2FYn5if%2B9ITsNC%2BZ1X1D7OJ455mE22ny%2FvkwJWa%2B2S8FhGsDOQ52ylL%2BOK5OeXCThmceF1czSmDjlF6UJWyS%2FnvGmZQRtDYzQoXtcLwxLvleoeGfdQL%2BfHQOi1ubrimGyytxsfZoZs%2B9PK8zPyRREc8AV652eKqtnCGH2yL4b%2FTC5wEY%2FnqAbUlZTKb8wBS6Z41KKqPRM6b817Lw4Ebvn%2BROBCtqq%2F1tqlO%2BYra3qincjjovKO0EjnbhMwzxH8T4EjCV8%2Fi9a3NMYXvqE1zzkOMq%2BHm0mBV8ui4KldrJ496iIytuY9Vr%2FqrSmugvtnKQgetgYpFdwbKDVCu8f89Mep44sgzg9r%2BNcHPPQmOvkKUieg2IgIvUvls5Ey3HKX5Tl8nAQ6Mi%2BX9rtt67DnwIece2pbnv%2FVAtXqfKxSrXjmdhz8%3D
